[tools]
usage = "latest"
python = "latest"
go = "latest"
node = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[env]
# python
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-python-packages"
# go
MISE_GO_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-go-packages"
GOPATH="{{env.XDG_DATA_HOME}}/go"
# node
MISE_NODE_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-npm-packages"
