import = ["~/.config/alacritty/themes/solarized_osaka.toml"]

[window]
dimensions = { columns = 90, lines = 25}
decorations = "Buttonless"
padding = { x = 4, y = 8 }
dynamic_padding = true
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Input Mono Nerd Font", style = "Regular" }
italic = { style = "Italic" }
bold = { style = "Bold" }
bold_italic = { style = "Bold Italic" }
size = 12
offset = { x = 0, y = 3 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutQuad"
color = "#555555"
duration = 100

[cursor]
blink_interval = 600
blink_timeout = 0

[cursor.style]
blinking = "On"

[mouse]
hide_when_typing = true
