import = ["~/.config/alacritty/themes/solarized_custom.toml"]


[window]
dimensions = { columns = 90, lines = 25}
decorations = "Buttonless"
padding = { x = 12, y = 12 }

[font]
normal.family = "Input Mono"
size = 12
offset = { x = 0, y = 3 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutQuad"
color = "#555555"
duration = 100

[cursor]
blink_interval = 600
blink_timeout = 0

[cursor.style]
blinking = "On"

[mouse]
hide_when_typing = true
