[tools]
usage = "latest"
python = "3.12"
node = "22"

[env]
# python
MISE_PYTHON_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-python-packages"
# node
MISE_NODE_DEFAULT_PACKAGES_FILE = "~/.config/mise/.default-npm-packages"

