# Prefix
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

set-option -s escape-time 15

set-option -g mouse on

# Enable focus events
set-option -s focus-events on

# Alacritty feature support
set-option -as terminal-features "alacritty*:clipboard:ccolour:cstyle:hyperlinks:mouse:RGB:strikethrough:usstyle"

